/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/yhf815ifLVV
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Libre_Franklin } from 'next/font/google'
import { Libre_Franklin } from 'next/font/google'

libre_franklin({
  subsets: ['latin'],
  display: 'swap',
})

libre_franklin({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/

"use client"

import Link from "next/link"
import { Label } from "../ui/label"
import { Input } from "../ui/input"
import { Button } from "../ui/button"
import { use, useState } from "react"
import axios from "axios"


export function Homepage() {

  const [username , setUsername] = useState("") ;
  const [password , setPassword] = useState("") ;
  const [email , setEmail] = useState("") ;
  const [mobile , setMobile] = useState("") ;
  const [name , setName] = useState("") ;

  return (
    (<div
      className="grid min-h-screen items-start gap-10 lg:grid-cols-2 lg:items-center">
      <div className="p-6 space-y-6 lg:p-10 lg:space-y-10">
        <nav className="flex items-center space-x-4">
          
          <div className="hidden text-2xl font-bold lg:block">
            <Link className="font-bold" href="#">
              Medicine Hub
            </Link>
          </div>
          <div className="space-x-2 ml-auto lg:space-x-4">
            <Link
              className="rounded-lg px-3 py-1 text-sm font-medium bg-gray-100 dark:bg-gray-800"
              href="http://localhost:5173/home/add">
              Donate
            </Link>
            <Link
              className="rounded-lg px-3 py-1 text-sm font-medium bg-gray-100 dark:bg-gray-800"
              href="http://localhost:5173/home">
              Buy
            </Link>
          </div>
        </nav>
        <div className="space-y-6 lg:space-y-8">
          <div className="space-y-4 lg:space-y-6">
            <h1
              className="text-4xl font-bold tracking-tight sm:text-5xl md:text-6xl lg:text-7xl/none">
              Help us save lives
            </h1>
            <p
              className="max-w-[700px] text-gray-500 md:text-xl dark:text-gray-400 lg:text-base xl:text-xl">
              Your donation can make a difference. Help us provide essential medicines to those in need.
            </p>
          </div>
          <div className="space-y-4 lg:space-y-6">
            <h1
              className="text-4xl font-bold tracking-tight sm:text-5xl md:text-6xl lg:text-7xl/none">
              Get the medicines you need
            </h1>
            <p
              className="max-w-[700px] text-gray-500 md:text-xl dark:text-gray-400 lg:text-base xl:text-xl">
              Access a wide range of quality medicines. Your health is our priority.
            </p>
          </div>
          <div className="space-x-4">
            <Link
              className="inline-block rounded-lg px-6 py-3 text-lg font-medium bg-gray-900 text-gray-100 shadcn:scale"
              href="http://localhost:5173/home/add">
              Donate
            </Link>
            <Link
              className="inline-block rounded-lg px-6 py-3 text-lg font-medium bg-gray-900 text-gray-100 shadcn:scale"
              href="http://localhost:5173/home">
              Buy Medicines
            </Link>
          </div>
        </div>
      </div>
      <div
        className="p-6 bg-gray-100 dark:bg-gray-800 lg:min-h-screen lg:flex lg:items-center lg:p-10">
        <div className="mx-auto max-w-md space-y-4 lg:space-y-6">
          <div className="space-y-2 text-center">
            <h1 className="text-3xl font-bold">Create an account</h1>
            <p className="text-gray-500 dark:text-gray-400">
              Already have an account?
              <Link className="underline" href="/signin">
                Sign in
              </Link>
            </p>
          </div>
          <div className="space-y-4">
            <div className="space-y-2">
            <div className="space-y-2">
              <Label htmlFor="name">Name</Label>
              <Input onChange={e => setName(e.target.value)} id="name" required type="text" />
            </div>
              <Label htmlFor="username">Username</Label>
              <Input onChange = {e => setUsername(e.target.value)}  id="username" required />
            </div>
            <div className="space-y-2">
              <Label htmlFor="email">Email</Label>
              <Input onChange={e => setEmail(e.target.value)} id="email" placeholder="m@example.com" required type="email" />
            </div>
            <div className="space-y-2">
              <Label htmlFor="password">Password</Label>
              <Input onChange={e => setPassword(e.target.value)} id="password" required type="password" />
            </div>
            <div className="space-y-2">
              <Label htmlFor="mobile">Mobile</Label>
              <Input onChange={e => setMobile(e.target.value)} id="mobile" required type="text" />
            </div>
            

            <Button onClick = {async () =>{
              const {token} = await axios.post('http://localhost:3000/user/signup' , {
                  name ,
                  email ,
                  password ,
                  mobile ,
                  username
              })
              localStorage.setItem("token" , token);
              window.location.href="/home"
            }} className="w-full" type="submit">
              Sign up
            </Button>
          </div>
        </div>
      </div>
    </div>)
  );
}
